export const DEFAULT_CONFIG = {
    pixelSize: 2,
    colorColors: 8,
    brightness: 1,
    contrast: 1.2,
    ratio: 'fullscreen',
    mirror: false,
    zoom: 1,
    temperature: 0,
    tint: 0,
    saturation: 1,
    highlights: 0,
    shadows: 0,
    red: 0,
    green: 0,
    blue: 0,
    tints: [{ color: '#ffffff', intensity: 0 }],

    hdr: 0,
    palette: 'default_cam',
    ditherMode: 'bayer4x4',
    crt: false,
    scanlines: 0,
    filmGrain: 0,
    vignette: 0,
    chromaticAberration: 0,
    bloom: 0,
    edgeDetection: false,
    customEdgeColor: '#000000',
    invert: false,
    hueShift: 0,
    sepia: 0,
    monochrome: false,
    sharpen: 0,
    grid: 'none',
    gridFlip: 0,
    timer: 0,
    flashlight: false,

    exportFormat: 'png',
    shutterSound: true,
    timestamp: false,
    fpsLimit: 0, // 0 means uncap
    symmetry: 'none',
    nightVision: false,
    thermal: false,
    asciiMode: false,
    colorBlind: 'none',
    doubleExposure: 0,
    glitchMode: false,

    // --- NEW 24+ FEATURES ---
    pixelShape: 'square', // square, circle, diamond
    gridOpacity: 0,
    gridColor: '#ffd1dc', // Pastel pink default
    pastelOverlay: 'none', // none, pink, blue, yellow, mint, lavender
    pastelOverlayIntensity: 0.5,
    softFocus: 0,
    lcdEffect: false,
    bayerLevel: 1,
    paletteShift: 0,
    shadowTint: '#000000',
    highlightTint: '#ffffff',
    vhsDistortion: 0,
    solarize: 0,
    posterizeLevels: 255, // 255 = off
    colorWash: 0,
    dreamyGlow: 0,
    neonPastel: false,
    holographic: false,
    chromaKeyColor: '#00ff00',
    chromaKeyThreshold: 0,
    chromaKeyReplacement: '#ffb3ba', // pastel replacement
    edgeThickness: 1,
    edgeOpacity: 1,
    hueQuantization: 0, // steps 0-360
    lightnessQuantization: false,
    colorBleed: 0,
    noiseType: 'white' // white, pastel, dark
};
